"""
Export self-contained Python scripts that anyone with IBM Quantum credentials
can run to replicate substrate experiments on real Heron hardware.

The generated scripts have NO dependency on nwt_substrate at runtime — they
are standalone, with the relevant circuit builder inlined and the IBM runtime
boilerplate prefilled.  Just `pip install qiskit qiskit-ibm-runtime`,
set `QISKIT_IBM_TOKEN`, and run.
"""

from __future__ import annotations

import inspect
import textwrap
from pathlib import Path
from typing import Optional

from . import circuits as _circ
from .experiments import experiment as _get_experiment, EXPERIMENTS


# Map experiment number -> (callable, default-args text)
_BUILDERS = {
    1: (_circ.full_k7_state_prep_with_measurement, "()"),
    2: (_circ.k7_graph_state, "(n_classical=7)"),     # Z-basis: just measure
    3: (_circ.entanglement_tomography_x_basis, "()"),
    4: (_circ.y_basis_3body_correlator, "(triple=(0, 1, 2))"),
    5: (_circ.syndrome_distribution_circuit, "(error_qubit=0, error_axis='X')"),
    # Proposed (use K_7 prep as a template; fill in experiment specifics)
    6: (_circ.entanglement_tomography_x_basis, "()"),
    7: (_circ.k7_graph_state, "(n_classical=7)"),
    8: (_circ.k7_graph_state, "(n_classical=7)"),
    9: (_circ.k7_graph_state, "(n_classical=7)"),
    10: (_circ.muon_decay_circuit, "()"),
    11: (_circ.full_k7_state_prep_with_measurement, "()"),
}


SCRIPT_TEMPLATE = '''#!/usr/bin/env python3
"""
NWT Substrate Heron Experiment {n}: {name}
================================{underline}

{description_wrapped}

Status:    {status}
Backend:   {backend}
Paper:     {paper}
Shots:     {shots}

Generated by nwt_substrate v0.1.0  (heron.export_experiment_script).

To run:
    pip install qiskit qiskit-ibm-runtime
    export QISKIT_IBM_TOKEN=<your-IBM-Quantum-token>
    python {filename}

If QISKIT_IBM_TOKEN is not set, the script just prints the circuit structure
without submitting (useful for inspection / sanity-checking).

For the proposed experiments (status=='proposed'), this script provides
the K_7 graph-state preparation as a starting template; the experiment-
specific measurement/analysis is marked TODO and must be filled in based
on the substrate prediction being tested.
"""

import os
import sys


# =============================================================================
# Circuit builder (inlined from nwt_substrate.heron.circuits)
# =============================================================================

{builder_source}


# =============================================================================
# IBM Quantum / Heron submission
# =============================================================================

def submit_to_heron(qc, backend_name="{backend}", shots={shots}):
    """Transpile + submit to IBM Heron, return a Sampler result."""
    from qiskit import transpile
    from qiskit_ibm_runtime import QiskitRuntimeService, SamplerV2 as Sampler

    token = os.environ.get("QISKIT_IBM_TOKEN")
    if not token:
        raise RuntimeError(
            "QISKIT_IBM_TOKEN not set.  Get a token at "
            "https://quantum.ibm.com/  and `export QISKIT_IBM_TOKEN=...`"
        )

    service = QiskitRuntimeService(token=token, channel="ibm_quantum")
    backend = service.backend(backend_name)
    print(f"Submitting to {{backend.name}} ({{backend.num_qubits}} qubits)...")

    qc_compiled = transpile(qc, backend=backend, optimization_level=3)
    sampler = Sampler(backend)
    job = sampler.run([qc_compiled], shots=shots)
    print(f"Job ID: {{job.job_id()}}")
    print("Waiting for result...")
    return job.result()


def analyze(result):
    """
    Experiment-specific analysis.

    {analysis_doc}
    """
    print()
    print("=== Result ===")
    print(result)
{analysis_extra}


# =============================================================================
# Main
# =============================================================================

if __name__ == "__main__":
    qc = {builder_name}{builder_args}

    n_qubits = qc.num_qubits
    n_gates = sum(qc.count_ops().values())
    print(f"Experiment {n}: {name}")
    print(f"Status: {status}")
    print(f"Circuit: {{n_qubits}} qubits, {{n_gates}} gates, depth {{qc.depth()}}")
    print(f"Gate counts: {{dict(qc.count_ops())}}")
    print()

    if "QISKIT_IBM_TOKEN" not in os.environ:
        print("QISKIT_IBM_TOKEN not set — printing circuit and exiting.")
        print()
        print(qc.draw(output="text", fold=120))
        sys.exit(0)

    result = submit_to_heron(qc)
    analyze(result)
'''


# Per-experiment analysis stubs (one-line description + extra code)
_ANALYSIS_STUBS = {
    1: ("Each classical bit corresponds to one stabilizer eigenvalue. "
        "Substrate predicts every bit = 0 (eigenvalue +1). Device fidelity "
        "F can be estimated from how often any bit is flipped.",
        "    pub_result = result[0]\n"
        "    counts = pub_result.data.c.get_counts()\n"
        "    print(f'Counts: {counts}')\n"
        "    perfect = counts.get('0' * 7, 0)\n"
        "    total = sum(counts.values())\n"
        "    print(f'P(all stabilizers +1) = {perfect/total:.4f}')"),
    2: ("Sample the 7-qubit Z-basis distribution and reconstruct entanglement "
        "entropy across (k, 7-k) bipartitions.",
        "    pub_result = result[0]\n"
        "    counts = pub_result.data.c.get_counts()\n"
        "    print(f'Sampled {len(counts)} distinct outcomes')\n"
        "    # TODO: bipartite entropy reconstruction"),
    3: ("Same as Experiment 2 but in X basis (combined with Z and Y for "
        "full single-qubit tomography).",
        "    pub_result = result[0]\n"
        "    counts = pub_result.data.c.get_counts()\n"
        "    print(counts)"),
    4: ("Estimate <Y_u Y_v Y_w> from joint counts.  For non-Fano triples on "
        "|K_7>, substrate predicts exactly 0.",
        "    pub_result = result[0]\n"
        "    counts = pub_result.data.c.get_counts()\n"
        "    parity_sum = 0\n"
        "    for bitstr, n in counts.items():\n"
        "        bits = [int(b) for b in bitstr]\n"
        "        sign = 1 - 2 * (sum(bits) % 2)\n"
        "        parity_sum += sign * n\n"
        "    expectation = parity_sum / sum(counts.values())\n"
        "    print(f'<Y_u Y_v Y_w> = {expectation:+.4f}  (substrate predicts 0)')"),
    5: ("Syndrome distribution after a single-qubit error.  Substrate predicts "
        "the syndrome flips exactly the stabilizers anticommuting with the error.",
        "    pub_result = result[0]\n"
        "    counts = pub_result.data.c.get_counts()\n"
        "    print('Syndrome distribution:')\n"
        "    for s, n in sorted(counts.items(), key=lambda x: -x[1]):\n"
        "        print(f'  {s}: {n}')"),
    6: ("TODO: Full 7-qubit tomography across all bipartitions to reconstruct "
        "the entanglement spectrum.",
        "    # TODO: full-state tomography\n"
        "    print('Result:', result)"),
    7: ("TODO: gate-level extraction of alpha from K_7 Wilson amplitude.",
        "    # TODO: alpha-extraction protocol\n"
        "    print('Result:', result)"),
    8: ("TODO: augment |K_7> with extra qubits for two-universe slicing.",
        "    # TODO: two-universe correlation analysis\n"
        "    print('Result:', result)"),
    9: ("TODO: encode neutron's substrate state, evolve, observe decay pattern.",
        "    # TODO: neutron-decay analysis (Walk-phase 4c provides |M|^2)\n"
        "    print('Result:', result)"),
    10: ("Muon decay on K_7 vacuum.  Sweep the V-A mixer angle θ ∈ [0, π] "
         "and read out the muon survival probability P(muon at θ) = cos²(θ).",
         "    # Muon-decay analysis: parse cbit 7 (muon ancilla)\n"
         "    pub_result = result[0]\n"
         "    counts = pub_result.data.c.get_counts()\n"
         "    n_muon = sum(n for s, n in counts.items() if s.replace(' ','')[-8] == '1')\n"
         "    n_total = sum(counts.values())\n"
         "    print(f'P(muon) = {n_muon/n_total:.4f}')"),
    11: ("Sidereal A/B/C anisotropy probe.  Submit this circuit at three "
         "sidereal-aligned timestamps (t, t+12h, t+24h sidereal) and apply "
         "the drift correction sigma_v = (B-A) - (C-A)/2 per stabilizer.",
         "    # Per-vertex stabilizer expectation values\n"
         "    pub_result = result[0]\n"
         "    counts = pub_result.data.c.get_counts()\n"
         "    print('Per-vertex <S_v>:', counts)\n"
         "    # See analysis/nwt_sidereal_AB_C_demo.py for full A/B/C analysis."),
}


def export_experiment_script(n: int,
                              output_path: str | Path,
                              backend: str = "ibm_marrakesh",
                              shots: int = 10000) -> Path:
    """
    Generate a self-contained Python script for the given experiment.

    The script has no nwt_substrate dependency at runtime — anyone with
    `pip install qiskit qiskit-ibm-runtime` and an IBM Quantum token can
    run it directly.
    """
    exp = _get_experiment(n)
    builder_fn, builder_args = _BUILDERS[n]

    builder_source = inspect.getsource(builder_fn)
    # Strip the type-quoted return annotation since this is now standalone
    builder_source = builder_source.replace(
        '-> "QuantumCircuit":', '-> "QuantumCircuit":\n'
        '    from qiskit import QuantumCircuit, ClassicalRegister'
    )
    # Replace the HAS_QISKIT guard (not relevant in the standalone script)
    builder_source = builder_source.replace(
        '    if not HAS_QISKIT:\n        raise RuntimeError("qiskit not installed")\n',
        '',
    ).replace(
        '    if not HAS_QISKIT:\n        raise RuntimeError("qiskit not installed; pip install qiskit")\n',
        '',
    )

    description_wrapped = textwrap.fill(exp.description, width=72,
                                        subsequent_indent="")

    analysis_doc, analysis_extra = _ANALYSIS_STUBS[n]
    analysis_doc = textwrap.fill(analysis_doc, width=68,
                                  subsequent_indent="    ")

    output_path = Path(output_path)
    underline = "=" * (len(exp.name) + 4)

    script = SCRIPT_TEMPLATE.format(
        n=n,
        name=exp.name,
        underline=underline,
        description_wrapped=description_wrapped,
        status=exp.status,
        backend=exp.backend or backend,
        paper=exp.paper_section or "TBD",
        shots=shots,
        filename=output_path.name,
        builder_source=builder_source,
        builder_name=builder_fn.__name__,
        builder_args=builder_args,
        analysis_doc=analysis_doc,
        analysis_extra=analysis_extra,
    )
    output_path.write_text(script)
    return output_path


def export_all_experiments(output_dir: str | Path,
                            backend: str = "ibm_marrakesh",
                            shots: int = 10000) -> list[Path]:
    """Export all 9 experiments as standalone scripts in `output_dir`."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    paths = []
    for exp in EXPERIMENTS:
        slug = exp.name.lower().replace(" ", "_").replace("(", "").replace(")", "")
        slug = slug.replace(",", "").replace("/", "_").replace(":", "")
        slug = slug.replace("-", "_").replace("=", "_eq_")[:60]
        filename = f"exp{exp.number:02d}_{slug}.py"
        path = export_experiment_script(
            exp.number, output_dir / filename,
            backend=backend, shots=shots,
        )
        paths.append(path)
    return paths
